export const music_list = [
  "Electro-Light - Symbolism",
  "Lost Sky, Sara Skinner - Dreams pt. II (feat. Sara Skinner)",
  "Different Heaven - Nekozilla",
  "Whales, Jo. Cohen - We Are",
  "Unknown Brain, Chris Linton - Superhero (feat. Chris Linton)",
  "DEAF KEV - Invincible",
  "Cartoon, Coleman Trapp - Why We Lose (feat. Coleman Trapp)",
  "Ship Wrek - Ark",
  "Zeus X Crona - Invisible",
  "Cartoon, Daniel Levi - On & On (feat. Daniel Levi)",
  "Spektrem - Shine",
  "Elektronomia - Sky High",
  "Warriyo, Laura Brehm - Mortals (feat. Laura Brehm)",
  "Disfigure - Blank",
  "Sub Urban - Cradles",
  "TULE, Chris Linton - Fearless pt. II (feat. Chris Linton)",
  "Robin Hustin, Tobimorrow - Light It Up",
  "Janji, Johnning - Heroes Tonight (feat. Johnning)",
  "Syn Cole - Feel Good",
  "Different Heaven, EH!DE - My Heart",
];
