export const music_list = [
  "Rob Gasser - Supersonic",
  "Anikdote - Life Is Over (feat. Sanna Hartfield)",
  "Disfigure, HYLO - I'm Here",
  "Elliot Berger - The Nameless",
  "Wiguez, Josh Levoid, MaryQueen - Get Out Here (Ft. MaryQueen)",
  "Lost Sky - Vision",
  "SirensCeol - Nostalgia",
  "Jim Yosef - Canary",
  "Rogers &amp; Dean - Jungle",
  "Razihel - A Song About You",
  "ROY KNOX - Closer",
  "Lusil, Whales, Jo. Cohen - Run Away (feat. Lusil)",
  "Siren - Run Away",
  "MELO.KIDS, Emdi - My Love",
  "Beneath My Shade, VOLT VISION - Dangerous",
  "Prismo, Raiko - Stronger (Raiko Remix)",
  "THYKIER - Station 2",
  "Lost Sky - Dreams",
  "Fareoh - Illuminati",
  "DNAKM, InfiNoise - Bring me back to life",
  "Unknown Brain, NotEvenTanner - Hollywood Perfect",
  "Thymen Wiendels, Barmuda - Erased (ft. Barmuda)",
  "joegarratt - me",
  "JSTN DMND, ALVYN - SKY BRI",
  "Diamond Eyes - Devil",
  "jeonghyeon, Raptures. - Into The Light",
  "if found - Can't Deny",
  "Like Lions, Severin, Alex Skrindo - Heart",
  "yanvince - fearless",
  "Lennart Schroot, Josh Levoid, Wiguez - Get Out Here (Lennart Schroot Remix)",
  "WAYOUT, HAVSUN, Cartoon - On & On (ft. Daniel Levi)(Cartoon x HAVSUN x WAYOUT Remix)",
  "RetroVision, Micah Martin - Over Again (feat. Micah Martin)",
  "Egzod, Anna Yvette - My City",
  "M.I.M.E, N3WPORT - Touchdown",
  "Audioscribe - Free Fall",
  "Harley Bird, NIVIRO - The Edge",
  "if found - feel someth!ng",
  "Paul Flint - The Feeling",
  "Halcyon, Valentina Franco - Runaway (feat. Valentina Franco)",
  "Clarx, Shiah Maisel - Everything I Got",
  "OVSKY, Mo Falk - Home",
  "Egzod, Maestro Chives, Don Diablo - Royalty (Don Diablo Remix)",
  "More Plastic - Summoning",
  "Raven &amp; Kreyn - Biscuit",
  "Mara Necia, T &amp; Sugah - Lost In The Middle (ft. Mara Necia)",
  "Luke Carpenter, John Ross, Corey Saxon - California",
  "NIVIRO - The Apocalypse",
  "Ashley Apollodor, Roee Yeger, Whales - Where Was I",
  "NIVIRO - The Labyrinth",
  "NOYSE - Dreamin'",
  "Defunk, The Arcturians - Emotions",
  "ZANA, Coopex, KHEMIS - Tidal Wave",
  "Domastic - Khalas",
  "Emdi, RØGUENETHVN, Leo The Kind - Let Your Heartbreak (feat. Leo the Kind)",
  "Midranger - Apocalypse",
  "THYKIER - Shimmer",
  "IZECOLD, Molly Ann - Close (feat. Molly Ann)",
  "Barren Gates, Jon Becker - Pray That You'll Be Dead To Me",
  "Zack Merci, Nieko, Blxk Trey - Kadak",
  "ESAI, Shiah Maisel - Away From Me",
  "Gameboy Tetris, nublu, Cartoon - Biology",
  "More Plastic - Old School",
  "Clarx - Shakedown",
  "Guy Arthur - Spend It All",
  "SRY, Toxic Joy - Walk Away",
  "RetroVision - Hope",
  "Culture Code, Regoton, Jonny Rose - Waking Up",
  "Heleen, Afterfab, Coopex - EX",
  "Kontinuum - Aware",
  "Luke Burr, Unknown Brain - Dancing On The Moon",
  "Axtasia, Soundr - Light Up The Sky (feat. Soundr)",
  "Simon Beatz, MIDNIGHT CVLT - One Shot",
  "Geoxor - You & I",
  "iFeature - Insanity",
  "MIDNIGHT CVLT - Beyond The Skies",
  "Neoni - Haunted House",
  "Emily Makis, Hayve, CARBIN - Murderer",
  "Strybo - Curse",
  "Phantom Sage, Byndy - Silence (feat. Byndy)",
  "Y&amp;V - Back In Time",
  "Krakn - Light",
  "Electro-Light - The Edge",
  "Diviners, Harley Bird - Falling (feat. Harley Bird)",
  "Mangoo, bby ivy - Happi",
  "David Bulla - High Life",
  "EHLE, Henri Werner - ITTY BITTY (feat. EHLE)",
  "Daimy Lotus, LaCrème, Kovan - Miracle (feat. Daimy Lotus)",
  "Philly K., Diviners - Savannah (feat. Philly K.)",
  "Lensko - Let's Go!",
  "Laszlo - Don't Look Down",
  "RUD, Stahl, Elektronomia - Caramel",
  "Beave - Talk",
  "Yonexx, Lunar - Need You",
  "RetroVision - Heroes",
  "DM Galaxy, Tyler Fiore - Paralyzed",
  "RYVM, Avaya, Time To Talk - Found You",
  "Goodknight. - Freedom",
  "Max Brhon - Humanity",
  "Chilly, SVRT, MADZI - Sinister",
  "3rd Prototype, Harley Bird, Valentina Franco - Renegade (feat. Harley Bird & Valentina Franco)",
  "JJD, Elektronomia - Free",
  "Inukshuk - The Long Road Home",
  "Tom Wilson, Heuse - Ignite",
  "RYVN - Avatar",
  "ROY KNOX - Waterfall",
  "Raven &amp; Kreyn - Bubble",
  "Alisky - On",
  "NIVIRO - The Return",
  "m els, Siimi - Here For Me (feat. m els)",
  "yanvince, comusal - magnificent",
  "LFZ - Popsicle",
  "Hush - Freaky",
  "Unknown Brain, Glaceo - Jungle Of Love",
  "ETikka, MADZI - A&B",
  "Neoni, N3WPORT - Alive",
  "Jnathyn - Rise",
  "PHI NIX - The Word Is Out",
  "Cartoon, Asena, Charlie Lane - Howling",
  "NIVIRO - Annabelle's Tea Party",
  "Egzod, Alan Walker - Dreamer (Egzod Remix)",
  "Chime, Adam Tell - Whole",
  "Arc North, Neoni, Egzod - The Revolution",
  "Anikdote - Which Direction",
  "ANGELPLAYA - PULL UP",
  "Raiko - Revenger",
  "Egzod, Chris Linton - Wake Up (feat. Chris Linton)",
  "Kozah - Heavens",
  "Vanze, Brenton Mattheus - Forever (feat. Brenton Mattheus)",
  "The LJ, M.I.M.E - Push The Gas",
  "iFeature, Thorne - Alive (ft. iFeature)",
  "DigEx - Fall In Love",
  "Acejax, Levianth - Real Love ",
  "Hoverboots - One",
  "Krys Talk - Fly Away",
  "Diamond Eyes - Everything [Instrumental]",
  "Alex Skrindo, Axol - You & Me (feat. Axol)",
  "RudeLies - Down",
  "Vena Cava - Noire",
  "Wiguez - Marcheur",
  "Krys Talk, Cole Sipe - Fly Away (Cole Sipe Remix)",
  "Andrew A, Barmuda - Waiting",
  "Razihel - Love U",
  "Cajama - Retrophonic",
  "Voicians - Seconds",
  "Nat James, 22 Void Beats, VERB - Ignite",
  "Azertion, Diviners - Feelings",
  "NIVIRO - Time For Polka",
  "Alan Walker - Dreamer",
  "WATEVA - dead!",
  "Au5, Danyka Nadeau - Closer (feat. Danyka Nadeau)",
  "P-One, Wiguez - Pray Tonight",
  "Kadenza - Harpuia",
  "Donna Tella, Lunaar, Elektronomia - Champions",
  "Wiguez, Maria-Lea - Nunca (ft. Maria-Lea)",
  "Modern Revolt - LOCA",
  "Shiah Maisel, EBEN, Coopex - Ruined My Life",
  "Comma Dee, AC13 - Waves",
  "Srikar, Jay Eskar - To The Top",
  "DM Galaxy, Aloma Steele - Bad Motives (feat. Aloma Steele)",
  "Facading - Walk Away",
  "WBN, WIBERG - Complicated",
  "Sam Welch, KHEMIS, Coopex - If Looks Can Kill",
  "Ludwiig, Sk-Hall - New Beginning",
  "Mountkid - Dino",
  "Roses, Time To Talk - Bittersweet",
  "NIVIRO - Sapphire",
  "Jensation - Delicious",
  "Giraffe Squad - Wait For Me",
  "Ivan Jamile, Kédo Rebelle, Jim Yosef - Forces (feat. Ivan Jamile & Kédo Rebelle)",
  "Rob Gasser - Happy",
  "Max Brhon - The Future",
  "Sketchez - Don't Understand",
  "HANNY, Donkong - Binary",
  "Facading - Tonight",
  "4URA, VinDon - AKTIV",
  "Raude - sun",
  "Jordan Schor, Nathan Brumley - Cosmic (feat. Nathan Brumley)",
  "Jensation - Donuts",
  "N3WPORT - Castle",
  "Unknown Brain, Chris Linton - Perseus (feat. Chris Linton)",
  "Halvorsen - She Got Me Like",
  "CHENDA - Mr. Bully",
  "Summer Was Fun, Laura Brehm - Prism ",
  "OTG Stiffy, The FifthGuys, Mandrazo - Burn 'Em (Explicit)",
  "Electro-Light - Symbolism",
  "jeonghyeon, Arya - Losing",
  "Halcyon, Valentina Franco, Culture Code - Runaway (feat. Valentina Franco) [Culture Code Remix]",
  "Miss Lina, Phantom Sage - Kingdom (feat Miss Lina)",
  "Aero Chord, Anuka, DDark - Incomplete (Moombahton VIP)",
  "Chime - Phototropic",
  "Lost Identites, Rival - Throne (Lost Identities Remix)",
  "Shiah Maisel, Clarx - Give Up",
  "ATSMXN, VØJ - Blade Fury",
  "Prismo - Stronger",
  "Andromedik, Cartoon - Whatever",
  "Idle Days - Over It ",
  "Sharks - Shiver",
  "yanvince, just alex - whole",
  "Desmeon - Back From The Dead",
  "Icehunt, Helen Tess - Hover (feat. Helen Tess)",
  "Josh Bogert, Axollo - Silence",
  "T-Mass, Rain Man, Vikki Gilmore - Follow",
  "Whales - Love Is Gone",
  "Kozah - Hyperdrive",
  "Lennart Schroot - Fata Morgana",
  "Danyka Nadeau, Electro-Light - Where It All Began",
  "JJL, SIIK - Like That",
  "Used - Forget",
  "Silent Child, ruindkid, SVRRIC - Fall To My Grave",
  "Toxic Joy - The Rave",
  "Diviners, Level 8 - Guide You Home",
  "3rd Prototype - Together",
  "RUD, Elektronomia - Rollercoaster",
  "Shiah Maisel, Jim Yosef - Unforgivable",
  "LarsM - Lovers",
  "Cormak - Flavors",
  "Poylow, Misfit, MAD SNAX - Halo (I'll Be There)",
  "Debris, Our Psych - Omerta",
  "More Plastic - Rewind",
  "Raptures., Sam Ourt - Taking Control ft. Halvorsen (pema. Remix)",
  "Jim Yosef, Anna Yvette - Linked",
  "The Arc - Nothing at All",
  "Exert, Janethan - Losing You (feat. Janethan)",
  "Maryn, Shel Bee - Shake You Off (feat. Shel Bee)",
  "Syn Cole - Gizmo",
  "Shiah Maisel, Anikdote, CHENDA, Le Malls, Catas, Clarx - Numb The Pain",
  "ENROSA, Abandoned - Out of the Grave",
  "JJD - Future",
  "Kage - ONI",
  "Cartoon - I Remember U",
  "Facading - You And Me ",
  "JJL - Thought It Was U",
  "Kasger - Reflections",
  "Elektronomia - Sky High pt. II",
  "Futuristik - C U Again (feat. Mikk mae)",
  "Ashley Apollodor, Beatcore - Everyday",
  "QR - XXI",
  "HYLO, AKACIA - Paradise (feat. Akacia)",
  "OVSKY - Time",
  "Cajama, Tisoki - Feelings",
  "Jim Yosef - Arrow",
  "jeonghyeon, Noisy Choice - Too Far",
  "VØR, Alisky - Grow",
  "Floatinurboat, Chris Linton - Holding On",
  "3rd Prototype, Lex Dave, Yohamna Solange - Time (feat. Yohamna Solange)",
  "CØDE, Joseph Feinstein - We're Invincible (feat. Joseph Feinstein)",
  "DDark - Shootin Stars",
  "Rogers &amp; Dean, Amvis - Bloodpressure (feat. Amvis)",
  "MDK, Chime - Arcade Dwellers",
  "Rogers &amp; Dean - No Doubt",
  "Clarx - H.A.Y",
  "Electro-Light - The Ways",
  "ROY KNOX - Earthquake",
  "Florenza, Rameses B - Can't Let You Go",
  "Rob Gasser, Michael White, Miss Lina - Modular",
  "Thorne - Wings",
  "Sub.Soud - Feel The Buzz",
  "Moav, Raptures. - Me Times Two (Ft. Moav)",
  "THYKIER - THE LIMIT",
  "Clarx - Zig Zag",
  "Tobu - Return To The Wild",
  "Laminar - Osiris",
  "yanvince - las fallas",
  "Anikdote - Imma Killa!",
  "Cajama - Alone",
  "DNAKM, GalaxyTones, Abandoned - Luna",
  "Distrion, Electro-Light - Rubik",
  "Sinner's Heist, Harley Bird - Streetlight People (feat. Harley Bird)",
  "Tobu - Roots",
  "Housewell, Side-B, Karl VanBurkleo - Drifting Away",
  "Riell, Diviners - Slow",
  "32Stitches - Olympus",
  "JOXION - Getting Down",
  "Netrum - Pixie Dust",
  "Zeli - Sharks",
  "Henri Werner - Burned",
  "Y&amp;V - Falling Up",
  "Spektrum, Sara Skinner - Keep You",
  "VERB - Catching Feelings",
  "Lensko - Circles",
  "Alltair, Wiguez, Maestro Chives, Egzod - Royalty (Wiguez & Alltair Remix)",
  "borne - Take Away",
  "Heuse, Caravn - Spirits Say",
  "Thorne, Sam Riley - Need You",
  "NEFFEX - Desperate",
  "KIRA - New World",
  "Prismo - Hold On",
  "Wiguez, Alltair, P-One - 4 Love (Ft. P-One)",
  "SIIK, Alenn - Mess",
  "Vivien, Janji - Together (Feat. Vivien)",
  "Razihel - Power Up",
  "Sam Day - BABY",
  "PollyAnna, NIVIRO - Fast Lane (feat. PollyAnna)",
  "imallryt, Derpcat, ROY KNOX - Only You",
  "JPB, Valentina Franco - Get Over You (feat. Valentina Franco)",
  "EMM, Egzod - Game Over ",
  "Mendum - Red Hands",
  "Mara Necia, Rob Gasser, T &amp; Sugah - Bring Me The Light (Rob Gasser Remix)",
  "More Plastic, URBANO - Psycho",
  "Kovan, Alex Skrindo, Izzy - Into The Wild (feat. Izzy)",
  "PLVTO - Are You With Me",
  "Laszlo - Here We Are",
  "Kozah - Paradox",
  "Britt Lari, Arcando - In My Head",
  "Rob Gasser - Ricochet",
  "Ghost'n'Ghost, Blooom, ASHWOOD - Realize",
  "Michael White, Deflo - About To Go Down",
  "OBLVYN - A Mere Blip In Your Timeline",
  "Lemon Fight, Champion - Stronger (Champion Remix)",
  "Speo, Budobo - Make A Stand (feat. Budobo)",
  "Uplink - Crying Over You",
  "Raven &amp; Kreyn - RICH",
  "Itro - Panda",
  "ReauBeau, AVA NOVA - Wizkid feat. AVA NOVA",
  "T-Mass - Ignoring My Heart",
  "GLNNA, Blosso, Slippy - Horizon",
  "Cream Blade - Heavenly",
  "Lost Sky, Sara Skinner - Dreams pt. II (feat. Sara Skinner)",
  "Elektronomia - Collide",
  "NIVIRO - Flares",
  "Wiguez, borne - Pressure (ft. imallryt)",
  "Jim Yosef - Let You Go",
  "MADZI - What You Gonna Do",
  "Domastic - Forever",
  "VENEMY, Car - Rescue Me (feat. Car)",
  "Rival, CADMIUM, Harley Bird, NIVIRO - Seasons (feat. Harley Bird) [NIVIRO remix]",
  "Whogaux, ÉWN, Johnning - Don't Want U Back",
  "Brogs, SFRNG, Kaphy - Too Late",
  "BVRNOUT, Mia Vaile - Take It Easy (feat. Mia Vaile)",
  "NIVIRO - Flashes",
  "Leo The Kind, Egzod - Mirage (feat. Leo The Kind)",
  "Mara Necia, T &amp; Sugah - Bring Me The Light",
  "imallryt, Hayve - Half Alive",
  "Heuse, Chris Linton - Reactive",
  "Low Mileage - Keep Me Closer",
  "Futuristik - Forgive Me",
  "blankfaces, Arya - Daydream",
  "Curbi - Dime",
  "Clarx, Guy Arthur - For Good",
  "PLEEG - Home",
  "LFZ - Echoes",
  "Electro-Light, Sidekicks - Hold On To Me",
  "Krys Talk, Ray Volpe - Fly Away (Ray Volpe Remix)",
  "N3WPORT, Britt Lari - Paradise",
  "Moe Aly, Clarx - Healing",
  "CØDE - Get The Party",
  "SOXX - Trouble With Love",
  "VIANI, Andrew A - Lost",
  "BEAUZ, MOMO - Won't Look Back ",
  "Joe Garston, Richard Caddock - Loud & Clear (feat. Richard Caddock)",
  "Elektronomia - Breeze",
  "Linn Sandin, Facading, Vosai - Fighting Fire",
  "RedMoon, Jonny Rose - Only Us",
  "TITUS, Guy Arthur, Todd Helder - Closer",
  "Syn Cole - Keep Going",
  "Marin Hoxha - Endless",
  "iFeature, just alex - Vision",
  "Andromedik - Firefly",
  "Steve Hartz - Never Get Old",
  "Rival, Alan Walker - Dreamer (Rival Remix)",
  "if found - Need You",
  "Fearon, Waterbeld, Carl Zeer - Talk To Me",
  "NEZZY, Coopex - You & Me",
  "Dayce Williams, Azertion, Diviners - Reality (ft. Dayce Williams)",
  "Jim Yosef, Valentina Franco - Chasing Dreams",
  "Magnus - Like This",
  "Molly Ann, JJD - A New Adventure",
  "Venjent, Oktae - Calling For You",
  "NATSUMI - Take Me Away",
  "Daniel Levi - I Like It With You",
  "Different Heaven - Nekozilla",
  "Prismo - Weakness",
  "Rogers &amp; Dean, Rival, CADMIUM - No Doubt (Rival x Cadmium Remix)",
  "Outlandr - World on Fire",
  "Foria - Break Away",
  "More Plastic - Razor",
  "Catas, Kasger - Blueshift",
  "Drolood - Break It",
  "Shiah Maisel, Zeus X Crona - Run & Hide",
  "Electric Joy Ride - Origin",
  "Mendum, GalaxyTones, Abandoned - Luna [Mendum Remix]",
  "Facading - Take It Down",
  "ROY KNOX - Breathe Me In",
  "Zaza - Be Together",
  "TOKYO MACHINE - SLASH",
  "Disfigure, HYLO - Blank (HYLO Remix)",
  "Robin Hustin - On Fire",
  "CADMIUM, Rival, Futuristik - Seasons (feat. Harley Bird) [Futuristik & Whogaux Remix]",
  "Malik Bash - Apollo",
  "EMM, Jim Yosef - Shudder",
  "JJL, Srikar, Jay Eskar - To The Top (feat. Srikar) (JJL Remix)",
  "Raven &amp; Kreyn - Muffin",
  "Dirty Palm - No Stopping Love",
  "Thorne, Andrew A - Behind",
  "JIKES, Nori - Lets Fly Away Pt.2",
  "Alex Skrindo, Miza - Thinkin'",
  "Outlandr - Overcome",
  "Whales, Jo. Cohen - We Are",
  "Disco's Over, Lokka Vox - Reflections (feat. Lokka Vox)",
  "Neoni, Egzod - The Revolution",
  "Barren Gates, BEAUZ, Harley Bird - Tomorrow (feat. Harley Bird) ",
  "Killercats, Alex Skrindo - Tell Me",
  "Unknown Brain, Spce CadeX, Max Landry - Holding You (feat. Max Landry)",
  "Electro-Light - Symbolism pt. II",
  "Raude - diversion",
  "Rob Gasser, Sekai - Superhero (feat. Sekai)",
  "Whales - Lights",
  "Raiko, Remi Willow - Lightning Child (feat. Remi Willow)",
  "Maze, Trinist - Lachrymose",
  "TULE - Fearless",
  "JPB, MYRNE, Yung Fusion - Feels Right (ft. Yung Fusion)",
  "Jon Becker, Tim Beeren, CHENDA - No Pressure",
  "Siberian Express - Talk To Me",
  "MANIA - Time Of Our Lives",
  "Zaug - 8 Rounds",
  "Aero Chord, Anuka, Muzzy - Incomplete (Muzzy Remix)",
  "Holly Drummond, Midranger - Unrequited (feat. Holly Drummond)",
  "imallryt, Arya, borne - One more try (feat. imallryt)",
  "ASHWOOD, Ghost'n'Ghost, Blooom - Maria (ft. Blooom & Ghost'n'Ghost)",
  "Wiguez, MIDNIGHT CVLT - Can't You Feel It",
  "James Roche - Away",
  "Maris Pihlap - Hold On Me",
  "Robbie Rosen, Lost Identities - Moments (Acoustic Version)",
  "The Eden Project - Chasing Ghosts ",
  "Lemon Fight, Jessica Reynoso - Stronger (feat. Jessica Reynoso)",
  "3rd Prototype - I Know",
  "Dark Heart - Crash Test Dummy",
  "Vizzen, Wiguez - Love Me Better",
  "Tobu - Lost",
  "Audioscribe - Skyline",
  "Unknown Brain, Chris Linton - Superhero (feat. Chris Linton)",
  "DEAF KEV - Invincible",
  "Heuse, Zeus X Crona, Emma Sameth - Pill (feat. Emma Sameth)",
  "Ramzoid - Electron",
  "Barren Gates, M.I.M.E - Enslaved",
  "Outlandr - Eternity",
  "Debris - Double D",
  "PatrickReza - Choices",
  "Egzod, Veronica Bravo, M.I.M.E - Rise Up (ft. Veronica Bravo & M.I.M.E)",
  "Blazars - Polaris",
  "Lostboy, Slashtaq - Elysium",
  "Kage - Cereb",
  "Everen Maxwell - Hyperphantasia",
  "Cartoon, Coleman Trapp - Why We Lose (feat. Coleman Trapp)",
  "Max Brhon - Redemption",
  "Indy Skies, Pirapus, Andromedik - Ride or Die (ft. Indy Skies)",
  "K-391 - Earth",
  "Alex Skrindo - Jumbo",
  "Jim Yosef, Scarlett - Volcano",
  "Kozah - Travel Again",
  "if found - Dead of Night",
  "Codeko - Crest",
  "Diviners, Contacreast - Tropic Love (feat. Contacreast)",
  "Approaching Nirvana, Alex Holmes - Darkness Comes",
  "Ghost'n'Ghost, Blooom, ASHWOOD - Not A Thing",
  "Aero Chord - Time Leap",
  "Axol, Alex Skrindo, Distrion, RudeLies - Together",
  "Axollo - Moonstruck",
  "Rob Gasser, Veronica Bravo - Hollow (feat. Veronica Bravo) ",
  "PHI NIX - Can't Break Me Down",
  "Culture Code, Michael Zhonga - Electricity (feat. Michael Zhonga)",
  "Tobu - Back To You",
  "Moav - I Don't Wanna Know",
  "Chime, Adam Tell, Rob Gasser - Whole (Rob Gasser Remix)",
  "Nieko, Zack Merci - Ray Of Light",
  "Titus1, MIDNIGHT CVLT - Better Days ",
  "Halvorsen, Netrum - Shivers",
  "Poylow - Victory",
  "Salvo, Maazel, Arcando - To Be Loved",
  "Centrix, Dani King, Rebel Scum - Calm Before The Storm",
  "3rd Prototype - Feel So Good",
  "Rob Gasser, Miss Lina - Rift",
  "NIVIRO - So Funky",
  "Nytrix, Mynerva - Find You",
  "Electro-Light, Ke'nekt - You And Me (feat. Ke'nekt)",
  "Sam Day - BE THE ONE",
  "Andromedik - SHE",
  "Defqwop - Awakening",
  "ORGAN - Cricket (we nice)",
  "Vena Cava, Project Veresen, Raya - Flames",
  "Paul Flint, CADMIUM - A Stranger's Dead",
  "Ntsika, Raude - paradise (feat. Ntsika)",
  "Nara, 2 Souls - Lonely",
  "Jim Yosef - Speed",
  "Ship Wrek - Ark",
  "Jessica Chertock, Robin Hustin - Burn It Down",
  "shi'tz, SIIK, WYKO - 2AM (feat. shi’tz)",
  "SKYLINK - The Wizard",
  "Daniel Levi - Talk",
  "Dwonji - COME UP",
  "John Kenza - Wicked",
  "Jim Yosef - Eclipse",
  "Frizzy The Streetz, Simbai - Set Me Free",
  "Rxm リム - LOOK AT ME!",
  "VENEMY, Emily Jane - Heartbeat (Ft. Emily Jane)",
  "Phantom Sage - MIKO",
  "T-Mass, Jaxxtone - Gave To Me",
  "Music Predators - Adventure Time",
  "Emdi, Coorby, Kristi-Leah - Lonewolf (feat. Kristi-Leah)",
  "Unknown Brain - Childhood Dreams",
  "Hayve, The Arcturians - Bit By Bit",
  "Rival, Asketa &amp; Natan Chaim - Superhero In My Sleep",
  "Lensko - Titsepoken 2015",
  "More Plastic - Champion",
  "Greg Aven, MILANE - Like You",
  "Culture Code, KARRA - Make Me Move (feat. KARRA)",
  "The Void - Lost Language",
  "Tetrix Bass, Veela - The Light",
  "Zeus X Crona - Invisible",
  "Ship Wrek, Mia Vaile - Pain (feat. Mia Vaile)",
  "Vosai, VinDon - Demnuhbad (feat. VinDon)",
  "Fransis Derelle, Parker Polhill - Fly (feat. Parker Polhill)",
  "Inukshuk - Happy Accidents",
  "Ayve, T &amp; Sugah - Cast Away ft. Ayve",
  "Hoober, Axol - How We Do It (ft. Marvin Divine)",
  "jeonghyeon, Noisy Choice - Useless",
  "32Stitches, GNDHI, J Fitz - Wish You The Best (feat. J Fitz)",
  "Yancle - Think About Me",
  "Mountkid - No Lullaby",
  "Jo. Cohen, BQ - Glowing At Night",
  "Itro, Valcos - Starbound",
  "Goodknight. - Try Again",
  "Dany Yeager, Chris Later - There's Nobody Else",
  "ANGELPLAYA - PLAYAS NEVER DIE",
  "Besomorph, Coopex, Riell - Redemption (ft. Riell)",
  "Rxm リム - CONNECTION",
  "Dax, VinDon, Unknown Brain - Phenomenon",
  "Andromedik, Murdock, Dualistic - Light (feat. Dualistic)",
  "Um41K, Aeden - Ain't Nobody Perfect",
  "Mendum - Elysium",
  "Cartoon, Daniel Levi - On & On (feat. Daniel Levi)",
  "Unknown Brain - Oh Darling ",
  "Hilefex, Jonth - Non Stop",
  "Ghost'n'Ghost, Blooom, ASHWOOD - Dial Tone",
  "Ascence - Konnichiwa ",
  "Robert Chacon - Redshift",
  "Egzod, Leo The Kind - Paper Crowns (feat. Leo The Kind)",
  "Domastic - Weird Dream",
  "WATEVA - Ber Zer Ker",
  "NIVIRO - Get My Love",
  "Danyka Nadeau, Au5 - Interstellar",
  "Michael White - All Eyes On Me",
  "3rd Prototype - Blue",
  "Anikdote - Turn It Up",
  "Zack Merci, CRVN - Nobody",
  "Olly Walker - Sorry (I Had To Leave)",
  "Eline Mann, ReauBeau - For You (feat. Eline Mann)",
  "Sekai - Somebody",
  "Axol, Max Hurrell - Shots Fired",
  "Subtact, Sara Skinner - Want You (feat. Sara Skinner)",
  "THYKIER - Inferior",
  "Disfigure - Summer Tune",
  "Felix Samuel, Millbrook - Lost Without You",
  "Barren Gates - You Made A Monster",
  "DigEx - Trust Me ",
  "Nomeli, Maikubi, FLAYA PLAYA - uWu BURST",
  "Shiah Maisel, CADMIUM - Blame It On Me",
  "Xaia, Rain Man, Oly - Breakdown",
  "nuumi, Cartoon - On & On (nuumi Remix)",
  "Paul Flint - E Welem Bah",
  "Distrion, Max Landry - Chasing Ghosts (feat. Max Laundry)",
  "2SCOOPS - Donuts",
  "WATEVA, Thorne - What I Say (Thorne Remix)",
  "Jim Yosef - Firefly pt. II",
  "Convex, Jex - 4U (feat. Jex Jones)",
  "DigEx, Raptures. - Feel",
  "Keerthin - Escape",
  "Everen Maxwell - A Day At Sea",
  "JPB - What I Want",
  "Le Duke, MIDNIGHT CVLT - Time Travel",
  "M.I.M.E, Requenze, Asketa &amp; Natan Chaim - Warriors",
  "Axol, Levianth, The Tech Thieves - Remember (ft. The Tech Thieves)",
  "Anikdote, Absent, Oriental Cravings - Heavens Gate (feat. Oriental Cravings)",
  "Tatsunoshin - The Time",
  "Ellen Louise, ROY KNOX, Tetrix Bass - When I'm Gone (Feat. Ellen Louise)",
  "TOKYO MACHINE, Guy Arthur - GET UP",
  "SPIRIT LINK, Swole Sauce, Tom The Gaffer - Stay With Me (feat. Tom The Gaffer)",
  "Electro-Light, Iain Mannix, VENEMY - Clearly (Venemy Remix)",
  "Unison - Translucent",
  "Jason Diaz, Cartoon - Don't Be A Stranger",
  "Jim Yosef, Anna Yvette - Courage",
  "Droptek - New Style",
  "Everen Maxwell - Accelerate",
  "Alex Skrindo, Axol - Get Up Again (feat. Axol)",
  "Upsilone - Duxure",
  "ÉWN, Whogaux - Start That Fire",
  "Shiah Maisel, Unknown Brain - Forget You",
  "Zaug, Jéja - Bad Habit (feat. Zaug)",
  "Britt Lari, T-Mass - Like Me",
  "Yix, TARI - Bliss",
  "borne, imallryt - Bonfire ft. imallryt",
  "IZECOLD, Molly Ann, Brooks - Close (feat. Molly Ann) (Brooks Remix)",
  "T &amp; Sugah - Indecisive",
  "ElementD, Micah Martin - Fallin' (feat. Micah Martin)",
  "Au5, Last Heroes, Holly Drummond - Lush (feat. Holly Drummond)",
  "Rival, Caravn - Lonely Way",
  "Four Eyes - Psycho",
  "T &amp; Sugah, NCT - Stardust",
  "Hoober, Riell - Wild Side (feat. Riell) ",
  "Thorne, Rico 56, Wiguez - Gone (Feat. Rico 56) (Thorne Remix)",
  "DJ Frog, Nito-Onna, Coopex - Whispered Promises",
  "Cartoon - Más Y Más",
  "Feint, Heather Sommer - Shockwave (feat. Heather Sommer)",
  "Arcana, Zack Merci - Love Potion",
  "Zookeepers, Heuse - Mercury",
  "Omri - Dishonest",
  "intouch - Now I'm Broken",
  "ZEST - You & Me",
  "Eli Raain, CADMIUM - Ghost (feat. Eli Raain)",
  "Alex Skrindo, Alan Walker - Dreamer (Alex Skrindo Remix)",
  "Lost Sky, Jex - Where We Started (feat. Jex)",
  "if found - Met You",
  "FERGO, Sam Ourt - Love Me",
  "Halcyon, Valentina Franco, TARI - Runaway (feat. Valentina Franco) [TARI Remix]",
  "Different Heaven, LFZ - Nekozilla (LFZ Remix)",
  "Paul Flint - Sock It To Them",
  "Leat'eq - Sunrise",
  "Kaivon, Pauline Herr - First Love (feat. Pauline Herr)",
  "Alva Gracia - Emotions Like",
  "Frizzy The Streetz, Simbai - Crazy",
  "Part Native, Oly - Artificial Love",
  "Spektrem - Shine",
  "Castion - Banger Machine",
  "JJL, Malarkey - Everything U Promised",
  "Rex Hooligan, NCT, T &amp; Sugah - Stardust (Rex Hooligan Remix)",
  "Jack Shore, KORA - Memory Nights",
  "Daniel Levi - Clown Around",
  "Outlandr, Aleya Mae - Falling",
  "Shiah Maisel, CHENDA - Ten More Minutes",
  "Dropouts, Aloma Steele - Unity (feat. Aloma Steele)",
  "Vena Cava, Raya - TOHKA (feat. Raya)",
  "Wiguez, Vizzen, EH!DE - Running Wild (EH!DE Remix)",
  "Different Heaven - OMG",
  "NIVIRO - The Ghost",
  "RetroVision - Puzzle VIP",
  "Jim Yosef - Moonlight",
  "Blackryst - Trust Me",
  "Lensko - Cetus",
  "Phantom Sage - Crystal Clouds",
  "Itro, Kédo Rebelle - Skyward Bound ",
  "Teyeq - Pull Me Down",
  "Main Reaktor - Salvation",
  "Toxic Joy - All Night",
  "Alex Skrindo, Stahl - Moments",
  "Sam Day - If You",
  "Shiah Maisel, Jim Yosef - Slow Down",
  "Razihel - Faster",
  "Kozah - Haha",
  "Syntact - Shallow",
  "Beatcore, Ashley Apollodor - Burning Bridges",
  "THYKIER - Outside",
  "Aeden, Sketchez - Take It or Leave It",
  "Ratfoot, Tritan - Hollow Life",
  "Romi, Cream Blade - Daydream",
  "C1W - Driver Seat",
  "Clarx - Bones",
  "intouch - Baby Sweet",
  "Waysons - Daydream",
  "Steve Hartz - Never Give Up",
  "RUD, Elektronomia - Memory",
  "Robbie Rosen, Lost Identities - Moments",
  "Uplink, NK - To Myself",
  "Kozah - Cali4nia",
  "Sendi Hoxha, DEAF KEV - Invincible Pt. II",
  "ONEEVA - Platform 9",
  "LAADS - Bad Girl",
  "Phantom Sage - The Light",
  "Josh Rubin - Black and White",
  "Abandoned, Shiah Maisel, InfiNoise - Finally Healing ",
  "Diviners - Stockholm Lights",
  "Kisma - Fly Again",
  "MANSHN - Online",
  "Like Lions, Severin - I Hear Sleigh Bells",
  "Harley Bird, Emdi, Castion, 3rd Prototype, Debris, Clarx - Evolution",
  "Kontinuum, Sunroof - Lost (feat. Savoi) [Sunroof Remix]",
  "Annie Sollange, Jonny Koch - LOVE ME",
  "T-Mass - Up In Flumes",
  "Jensation - Joystick",
  "Brenton Mattheus, InfiNoise, Abandoned - See You At The End",
  "Elektronomia - The Other Side",
  "XTOM, ATSMXN - The Raven",
  "JPB, Soundr - All Stops Now (feat. Soundr)",
  "bvd kult - VIP",
  "21RoR - Talk About",
  "Floatinurboat, Chris Linton - Holding On [Instrumental]",
  "Ellerslie, Millbrook - Overdrive (ft. Ellerslie)",
  "PLEEG - Alive",
  "Elektronomia - Sky High",
  "EMM, Besomorph - Afterlife",
  "Futuristik, Sethh - Little Bit",
  "Michael White - Got You",
  "Icehunt - Back To Time",
  "Elliot Berger - Hold On (feat. Ranja)",
  "Alexis Donn, Unknown Brain - Dance With Me ",
  "Distrion, Alex Skrindo - Entropy",
  "Jade Key, Tatsunoshin - Summer's End",
  "RetroVision - Puzzle",
  "Raven &amp; Kreyn, KDH, Scarlett - Dum Dum",
  "Defunk, The Arcturians - Back For More",
  "Emily J, Unknown Brain - Don't Bother ",
  "Mia Vaile, BVRNOUT - Take It Easy (feat. Mia Vaile) (DNB Edit)",
  "Valcos - A New Light",
  "Blooom - Be Around",
  "Warriyo, Laura Brehm - Mortals (feat. Laura Brehm)",
  "Anna Yvette - Red Line",
  "Unison - Aperture",
  "RetroVision - Campfire",
  "Tinoma - Find You",
  "Diamond Eyes - Father",
  "Rob Gasser, Laura Brehm - Vertigo",
  "Different Heaven, Phantom Sage - Far Away (Phantom Sage Remix)",
  "Ashley Apollodor - Just Stay",
  "Marin Hoxha - With You",
  "Different Heaven, ReesaLunn - Pentakill",
  "Sam Day - Nothing To Hide ",
  "Ascence - About You",
  "Unknown Brain, Heather Sommer - Perfect 10 (feat. Heather Sommer)",
  "New Beat Order, Poylow, MAD SNAX - Lonely Hour",
  "Syn Cole - Reflect",
  "Outlandr, Dani King - Dynamiser",
  "CADMIUM, JAMZ, SIMONNE - Believe Me",
  "Raven &amp; Kreyn - Get This Party ",
  "NIVIRO - The Floor Is Lava",
  "Linko - Goodbye",
  "NIVIRO - On Replay",
  "Rameses B - Story",
  "3rd Prototype, Emdi - House",
  "Papa Khan - AWOL",
  "DEAF KEV - Safe & Sound",
  "Culture Code, KARRA, James Roche - Make Me Move (feat. KARRA) (James Roche Remix)",
  "Clarx - Ride",
  "Friendzone, The Eden Project - Iris",
  "WATEVA, Johnning - See U (feat. Johnning)",
  "Warptech, Cory Friesenhan - In The Stories (feat. Cory Friesenhan)",
  "Chris Ponate, Adikop - Ignite My Heart (feat. Chris Ponate)",
  "Mark Pettitt - Something Inside",
  "MADZI - Let's Play",
  "Spektrem, Gabriel Drew, Bloom - Shine (Gabriel Drew & Bloom Remix)",
  "Vosai - Love Of My Life",
  "Luke Burr, Unknown Brain - Dancing On the Moon",
  "RetroVision - Cake",
  "The Eden Project - Lost",
  "Young Viridii, 4URA - Yesterday",
  "Kasger - Out Here",
  "Axol, The Tech Thieves - Bleed",
  "Andromedik - Titan",
  "Shiah Maisel, CHENDA - Find You There",
  "Poylow, Lucky Low, MAD SNAX - Freak Show (feat. India Dupriez)",
  "Arya - Don't Know Why",
  "Laney, Clarx - Forever Finally Ends",
  "Dirty Palm, LexBlaze - Freakshow (feat. LexBlaze)",
  "Desembra - Hit 'Em",
  "Egzod, Leo The Kind, Nurko - Paper Crowns (feat. Leo The Kind) [Nurko Remix]",
  "PLEEG - Voyage",
  "Diamond Eyes - 23",
  "RetroVision, Domastic - SICC",
  "Tobu, DEAF KEV, Anna Yvette, Electro-Light, Jim Yosef - Destiny",
  "Distrion, RudeLies - One, Two",
  "Rival, Bryan Finlay - Walls (feat. Bryan Finlay)",
  "BH - Holding On",
  "ROY KNOX, Jim Yosef - Sun Goes Down",
  "VOE - Giants",
  "3rd Prototype - I'm Fine",
  "Clarx, Zaug - No Money",
  "EMM, Egzod - Don't Surrender",
  "Michael White - Angel's Anthem",
  "RudeLies, Facading - Arabian Nights",
  "iFeature - Rush",
  "SirensCeol - Coming Home",
  "Inukshuk - We Were Infinite",
  "Spirix - Rampage Diet",
  "Jnathyn - Dioma",
  "Domastic, Anna Yvette - Echoes",
  "Andrah - bye bye",
  "Aleesia, JPB - High",
  "Bromar, SouMix - Falling For You",
  "Ascence - Places Like That",
  "Todd Helder - Never Stop",
  "Phantom Sage - When I’m Gone",
  "Aeden - Would You Be Waiting",
  "Anixto - Ride Or Die",
  "Mojnz, WBN - Radio",
  "Shiah Maisel, Jim Yosef - Just Getting Started",
  "if found, Luma - twenty five",
  "Johnny Third, Jeremy Fowler - Young Ones (feat. Jeremy Fowler)",
  "Unknown Brain, Bri Tolani - Why Do I",
  "Jim Yosef, Ephixa - Everlasting",
  "Thorne - DownBeat",
  "Heuse, Chris Linton, Emma Sameth - Stones",
  "BLUK, Fiko - Too Hot To Handle",
  "Debris, RudeLies, Jex - Animal (feat. Jex)",
  "ANGELPLAYA - PSYCHOPATHIC",
  "Verm - Explode",
  "Aero Chord, Anuka, T-Mass - Incomplete (T-Mass Remix)",
  "CHENDA - For You",
  "Showdown, IMAN - Freedom",
  "Neoni, Rival - Throne",
  "Omar Varela, Xavi &amp; Gi, Miss Lina - Stronger (feat. Miss Lina)",
  "Axol - ILY",
  "Culture Code - Fairytale (feat. Amanda Collis)",
  "Rameses B - Hardwired",
  "Tom Mårtensson, Tobu - If I Disappear",
  "Brenton Mattheus, Mendum - You",
  "OVSKY - Way To You",
  "if found, nøll, damnboy! - die 4 u (feat. damnboy!)",
  "Paul Flint, Chris Linton - Watch The World Burn (feat. Chris Linton)",
  "Robbie Rosen, Deerock, Vaance - Electric",
  "The Arcturians - This is Life",
  "Star Party - Legends",
  "Lochlainn - The Garden",
  "Raven &amp; Kreyn, Moji, Illusion - Dream Forever",
  "bvd kult, Will Heggadon - Made Of Something (feat. Will Heggadon)",
  "Diamond Eyes - Hold On",
  "Geoxor - Higher",
  "Fiko - Waiting For You",
  "Andromedik - With Me",
  "borne - Out Of Here",
  "Denniz Jamm, Andreas Stone - Black Sunrise",
  "T &amp; Sugah - TumDaDaDum",
  "Rico 56, Doxed, Jay Eskar - Let's Run Away",
  "ATSMXN, XTOM - Enemies",
  "Main Reaktor - Recession",
  "Egzod, evOke - Departure (feat. evOke)",
  "Lost Sky - Need You",
  "Halvorsen, Netrum - Phoenix",
  "Zaug, Jéja - Bad Habit (feat. Zaug) - Phonk Version",
  "Ship Wrek, The Highrollers - Waiting",
  "Crunr, BEAUZ - Illusion (feat. Crunr)",
  "Shiah Maisel, ROY KNOX - Living With Regret ",
  "Rameses B, Soundr - Beside You (feat. Soundr)",
  "Uplink, AWR - Still Need You (feat. AWR)",
  "Luna Lark, Julius Dreisig - Where'd You Go",
  "Laszlo - Imaginary Friends",
  "Jauque X, Tom Wilson - Zero Gravity",
  "Linn Sandin, Unknown Brain - Candy",
  "Dropouts - Let Go",
  "Perk Pietrek, Abstrakt - Pressure",
  "NIVIRO - I Just Wanna",
  "Jordan Schor, Harley Bird - Home",
  "braev, N3WPORT - Power",
  "Coopex - Over The Sun",
  "Desmeon, ElDiablo, Flint, Zadik - On That Day (Ft. ElDiablo, Flint & Zadik)",
  "Electro-Light - Throwback",
  "NIVIRO - Diamond",
  "Mendum, JPB - Losing Control",
  "Kisma - Fingertips",
  "Simbai, Eyemèr - Thunder",
  "Highlnd, Rachel Lorin -  How To Love",
  "Killercats, Alex Skrindo - What I Said",
  "Rival, CRVN - Falling",
  "wes mills, Sam Day - Running Away",
  "Vanze, Balco, Fransis Derelle, Brenton Mattheus - All I Need (feat Brenton Mattheus)",
  "Cajama - You Did Me Wrong",
  "Kyle Reynolds, Asketa &amp; Natan Chaim - Alone (feat. Kyle Reynolds)",
  "Andreas Stone, Egzod, Rival - Live A Lie",
  "Nomra - Your Body",
  "Jim Yosef, Alex Skrindo - Passion",
  "OLWIK, Tyler Fiore - Villain (feat. Tyler Fiore)",
  "Tobu - Turn It Up",
  "Paul Flint - Savage",
  "Krakn - Aurora",
  "Elektronomia - Limitless",
  "iFeature - Indifferent",
  "Glude - Breathe",
  "Meggie York - numbers",
  "Anna Yvette - Running Out Of Time",
  "JJD - Can't Say No",
  "Peter Piffen, Too Martian, IntoAlter - When We Leavin",
  "Maestro Chives, Egzod, Neoni - Royalty",
  "Ship Wrek, Zookeepers, Trauzers - Vessel",
  "Coopex - Over The Sun (Pt. 2)",
  "Phantom Sage - Far From Home",
  "Emily Stiles, Rob Gasser, Spitfya, Sekai - Mistakes",
  "Veronica Bravo, Zeus X Crona - Who doesn't wanna fall in love",
  "Electro-Light - Symbolism pt. III",
  "Distrion, Alex Skrindo - Lightning",
  "Disfigure - Blank",
  "Different Heaven, Sian Area - Feel Like Horrible",
  "Disfigure, Tara Louise - Losing Sleep (feat. Tara Louise)",
  "VinDon, Magnus - Talk Is Cheap",
  "SGNLS, Guy Arthur, Aiobahn - All or Nothing (feat. SGNLS)",
  "Wasiu, Egzod - Mutiny",
  "Different Heaven - Far Away",
  "Emily Stiles, Phantom Sage - Our Lives Past (feat. Emily Stiles)",
  "Neon Dreams, Vanze - Survive (feat. Neon Dreams)",
  "JJD - Halcyon",
  "JOXION - RPM",
  "K.Safo, Alex Skrindo, Uplink, Stewart Wallace - Future Vibes (feat. Stewart Wallace) [Uplink Remix]",
  "Akacia - Electric",
  "Axol, Alex Skrindo - You",
  "Clarx - Disco",
  "JJD - Adventure",
  "Chandler Jewels, Dirty Palm - Ropes",
  "Daniel Levi - Getaway",
  "Hayve - Space Jam",
  "Vena Cava, Jordan Virelli - Handsonic",
  "Woolley, Heuse - Don't Hold Me Down",
  "ÉWN - Feels",
  "Distrion, Electro-Light - Drakkar",
  "JOXION - 094",
  "OLWIK, Johnning - This Life",
  "ROY KNOX - Blue Eyed Demon",
  "Phantom Sage, Byndy - Away (feat. Byndy)",
  "Outwild - Golden",
  "Barren Gates - Slow Down",
  "Whogaux - i don't care ",
  "Arcando, Fabian Mazur - Elevate",
  "Halvorsen, Netrum - Colorblind",
  "Andrew A, FROZT - Sleeping Till Noon",
  "Jim Yosef - Fall With Me",
  "Nurko, Last Heroes, Jessie Chambers - Promise Me (feat. Jessie Chambers)",
  "Kisma - We Are",
  "Tollef - Like A Stone",
  "Vaskan - Walk Away",
  "OBLVYN, Johnning - WHAT THE HELL (OBLVYN Remix)",
  "Dirty Palm, Micah Martin - Oblivion (feat. Micah Martin)",
  "STAR SEED - Chasing Stars",
  "Focus Fire - Mirage ",
  "Sekai - Burn Me Down",
  "Arcando - When I'm With You",
  "Arcando, EMIDEX - When I'm With You (EMIDEX Remix)",
  "Halvorsen, VØNH, Raptures. - Left Me Blind",
  "Elektronomia - Summersong 2018",
  "WiDE AWAKE - Something More",
  "WATEVA - What I Say",
  "Purple Velvet Curtains, Dirty Palm - To The Back",
  "Warptech - Last Summer",
  "Harddope - Heart Robbery",
  "The Same Persons - Versace",
  "JPB - LONG NIGHT",
  "Phantom Sage - Hollow",
  "Wiguez, Rico 56 - Gone",
  "Dust of Apollon, Sam Day - Take You Home",
  "Todd Helder - DISTODD",
  "Heleen, Distrion - Alibi",
  "James Mercy, PhiloSofie - Take You On",
  "WATEVA - Ping Pong Party",
  "Alexis Donn, Culture Code - You & I",
  "Mblue - Follow Me",
  "ReauBeau, Brynja Mary - Make Waves (feat. Brynja Mary)",
  "Jone - Everything",
  "Halvorsen, Division One, JJD - Somebody Like Me (feat. Halvorsen)",
  "NIVIRO - You",
  "Jim Yosef, Sara Skinner - WILDFIRE",
  "Modern Revolt - WAVY",
  "Leowi, joegarratt - Hollywood (feat. joegarratt)",
  "Jim Yosef - Imagine",
  "William Ekh, Alexa Lusader - Adventures (feat. Alexa Lusader)",
  "Cartoon, Xilent - I Remember U (Xilent Remix)",
  "Rob Gasser, Laura Brehm, Spitfya - Vertigo (Spitfya Remix)",
  "Unknown Brain, M.I.M.E - War Zone (ft. M.I.M.E)",
  "ROY KNOX - The Other Side",
  "Reece Taylor - Sugar Plumbin'",
  "Valcos, Chris Linton - Without You",
  "OVSKY - Lucky Charm",
  "Raude - ready!",
  "NIVIRO - Memes",
  "Domastic - Memories",
  "Joellé, Aeden - I Feel Crazy",
  "Killercats - Kaibu",
  "Meggie York, N3WPORT - Runaway",
  "Killabyte, Danyka Nadeau - Wicked Ways (feat. Danyka Nadeau)",
  "Diamond Eyes - Stars",
  "Wanden, Slashtaq - Full Speed Ahead",
  "VinDon, Jonth - Badniss",
  "Curbi - What You Like",
  "She Is Jules, Lost Sky - Vision pt. II",
  "Alaina Cross - Karma",
  "Tisoki, Cesqeaux - Give It To Me",
  "BPRTS, Gelow - Sunshine",
  "CADMIUM - Change Your Mind",
  "Micah Martin, Awon, OMAS - The Rage (feat. Micah Martin)",
  "CADMIUM, Grant Dawson - Be With You (feat. Grant Dawson)",
  "Kage - Dust",
  "Rival, Caravn - Be Gone (feat. Caravn)",
  "Jnathyn - Dioma (Demo)",
  "JOXION - Talk That Way",
  "Desmeon - Undone",
  "Subtact - Away",
  "Diamond Eyes - Gravity ",
  "Sam Day - Nothing To Hide",
  "JaySounds, Kage - Fly",
  "Annie Sollange - Falling For You",
  "3rd Prototype - Dancefloor",
  "Duke Gray, MANGASLAYERS, diGi - Dracula",
  "Slashtaq, Wanden - Better Off",
  "iFeature - Cozy Thunder",
  "Ship Wrek, Essy - Fools Gold",
  "Fresh Stuff, Alltair, Wiguez - 4 Love (Fresh Stuff Remix)",
  "Uplink - Sinking Ship",
  "Elektronomia - Energy",
  "METR, Adrian Benson, Ima Sobé - Broken Love (feat. Ima Sobé)",
  "More Plastic - Power",
  "Malik Bash - Ghosts ",
  "Paul Flint, Phil Lees, LW - Girlfriend (feat. LW)",
  "T-Mass - Bow and Arrow",
  "LarsM, Side-B, Aloma Steele - Over",
  "Heleen, BEAUZ, Alan Walker - Dreamer (BEAUZ & Heleen Remix)",
  "Axol - Mars",
  "Evanly - Hurt Me",
  "Blazars - Northern Lights",
  "Rival, CADMIUM, Harley Bird - Seasons (feat. Harley Bird)",
  "Abandoned, InfiNoise, Project Nightfall - Night Caller (feat. Project Nightfall)",
  "MADZI, JOXION - Flow",
  "Audioscribe - Shimmer",
  "Anikdote, Culture Code, Brado Sanz - Don't Let It Go (feat. Brado Sanz)",
  "Halvorsen - Wouldn't Change It",
  "Syn Cole - Need Ya",
  "Jonth - Collapse",
  "Our Psych - Purge",
  "OSKI - Stay The Night",
  "Krys Talk, Mendum - Fly Away (Mendum Remix)",
  "NO QVLT, JESSY KVGE - Insides (feat. JESSY KVGE)",
  "Used, Andromedik - Take Me",
  "Killabyte - Our Story",
  "TOBSIK, Spyker, Kato - Odyssey",
  "The Saint, Magnus - Pretty woman",
  "Modern Revolt - BURY",
  "PHI NIX, Hoober - Overdosin",
  "Abstrakt - Nobody Else",
  "CITYWLKR, Voicians - Consume Me",
  "Egzod, Tanjent - Universe",
  "Kasger - Highland",
  "Fareoh - Cloud Ten",
  "Ray Le Fanue, Britt Lari - What I Want",
  "LOUD ABOUT US! - Goes Like",
  "Wasiu, Egzod, CHENDA - Mutiny",
  "Kage - Commotion",
  "Harddope, Clarx - Castle",
  "Modern Revolt - VOLT",
  "Glude - Identity",
  "Nito-Onna, Poylow - Got Me",
  "Ash O'Connor - Vibe",
  "Unison - Reality",
  "THEBOYWITHSPEC, Axel Oliver - Survive",
  "Vanessa Campagna, Hoober - Higher",
  "JOXION, Thorne, iFeature - Unstoppable",
  "QUB3, B0UNC3, Quickdrop - Stay Or Be Alone",
  "Domastic, RudeLies, Vosai, Jagsy, Magnus, Facading, Tom Wilson, Jonth - Heartless",
  "John Dee, Litil, Elle Vee - Set It Free",
  "Slowboy, Rizó, NØCTRIS - Sold Dreams",
  "Austin Salter, Heuse - That Night",
  "Netrum, Halvorsen - Phoenix (But It's Punk Rock)",
  "Max Brhon - Illusion",
  "Laszlo - Fall To Light",
  "Daniel Levi - Down For Anything",
  "Time To Talk, Asena, Cartoon - Omen",
  "NIVIRO - The Guardian of Angels",
  "Diandra Faye, NIVIRO - Orphic Night (feat. Diandra Faye)",
  "Unknown Brain, Aviella - Inspiration (feat. Aviella)",
  "Le Malls - FOR YOU",
  "Whales, ggnoaa - Paranoia",
  "CØDE - Duck Face",
  "NOYSE, ÆSTRØ - La Manera De Vivir",
  "Hayve - Red Light",
  "Michael White, MYLK - Venus (feat. Mylk)",
  "Anixto - Joker",
  "Molly Ann, Tim Beeren, IZECOLD, Diviners, Caravn - This Time",
  "Morley, Speo - Hope",
  "T-Mass, Enthic - Can You Feel It",
  "Uplink, Heather Sommer - Chance On Faith",
  "Halvorsen - Band-Aid",
  "Valence - Infinite",
  "Clarx - Money",
  "ElementD, Mees van den Berg - Giving In (feat. Mees van den Berg)",
  "Spitfya, Desembra - Cut The Check",
  "Thorne - Call On Me",
  "Disco's Over, PRXZM - Lonely Island Pt. 2 (feat. PRXZM)",
  "Ava King, Unknown Brain - Blackhole",
  "Mendum - Stay With Me",
  "She Is Jules, Lost Sky - Darkness",
  "InfiNoise - Sunlight (Feat. Nilka)",
  "Srikar, AKIAL, Sam Ourt - Escape",
  "JPB - Up & Away",
  "Diviners, Philly K. - Savannah (feat. Philly K)",
  "ELPORT, VYMVN - Power",
  "RDLS, Facading - Come Alive",
  "JPB, Ashley Apollodor - Defeat The Night (feat. Ashley Apollodor)",
  "Halvorsen, Clarx - Done",
  "MAD SNAX, Harry Taylor, Poylow, India Dupriez - Drop In The Ocean (feat. India Dupriez)",
  "Krys Talk, JPB - Fly Away (JPB Remix)",
  "Kozah - Nobody",
  "Ascence - Rules",
  "Aero Chord, Anuka - Incomplete",
  "Charles B, Justmylørd - Falling For You",
  "Jimmy Rivler, Max Vermeulen, Almost Weekend - Let Me Go",
  "Disfigure, Tara Louise - Blank VIP",
  "Blooom, Ghost'n'Ghost - Desire",
  "Main Reaktor - Awakening",
  "Time To Talk, Georgia Michel - Time To Talk",
  "Last Heroes, AERYN, TwoWorldsApart - Eclipse (feat. AERYN)",
  "Michael Shynes, Max Vermeulen, Almost Weekend - Island (ft. Michael Shynes)",
  "Jim Yosef - Samurai",
  "EXXO - Tension",
  "LarsM, Side-B, Aloma Steele, Dropouts - Over (Dropouts Remix)",
  "T &amp; Sugah, Mara Necia - Bring Me The Christmas Light (ft. Mara Necia)",
  "Ash O'Connor, Curbi - Steeper",
  "AC13 - Visions",
  "Barmuda, Mandrazo, Poylow - Loneliness",
  "Brandon Jonak, Ezra James, Pep.B - Where Do I Go (feat. Ezra James)",
  "Raude - high4aminute",
  "Y&amp;V - Lune",
  "Jim Yosef, Anna Yvette - Can't Wait",
  "Gabriella, Knoir, Zeneth - Beam",
  "Halcyon, GIAN - December (feat. Gian)",
  "Andromedik - Let Me In",
  "NO QVLT - Neomorph",
  "Blooom - Drowning",
  "Papa Khan - Wounds",
  "Abandoned, EMM, Egzod - Don't Surrender",
  "Natan Chaim, Asketa - More",
  "NCT, T &amp; Sugah, Voicians - Along The Road",
  "Asena, Cartoon - Howling ",
  "Mike Robert, ROY KNOX - Over My Head",
  "if found - Dead Of Night (VIP)",
  "Barren Gates - Obey",
  "Spencer Maro - Starfire",
  "Tom Wilson - Run For Your Life ",
  "JOXION - ILY",
  "Koven - Never Have I Felt This (VIP)",
  "speedboys - techno on my mind",
  "Lennart Schroot, Unknown Brain, SRU - Kuyenda (feat. Sru)",
  "ANGELPLAYA - LET THEM HAVE IT",
  "JPB - Top Floor",
  "Syn Cole - Time",
  "Koven - Never Have I Felt This",
  "Max Brhon - Cyberpunk",
  "Alex Skrindo - Ruby",
  "Fectro, Wiguez - Pressure (Fectro Remix)",
  "Elektronomia - Vitality",
  "Inukshuk - Too Far Gone",
  "Uplink, Shiah Maisel - Go Easy",
  "JOXION - All Access",
  "Riell, WOLFHOWL, Heuse - Daylight",
  "Raven &amp; Kreyn - So Happy",
  "Teyeq - Demons",
  "Umpire - Collins Ave.",
  "Unknown Brain - DEAD",
  "Umpire, Liz Kretschmer - Gravity (feat. Liz Kretschmer)",
  "Sub Urban - Cradles",
  "ÉWN - The Light",
  "Daniel Levi - Honey",
  "Defqwop, The Ruins - Say The Word (feat. The Ruins)",
  "Barmuda, SOXX, Raptures. - Signs Ft. Barmuda",
  "Itro, Kontinuum - Alive",
  "SlidV, Zaug, Clarx - One Of Us",
  "Inukshuk - A World Away",
  "Far Out, Alina Renae - Chains (feat. Alina Renae)",
  "Barren Gates - Devil",
  "Maduk - Go Home",
  "Deflo, Lliam Taylor - Reflections",
  "Donna Tella, Arc North - Symphony",
  "Micah Martin, Convex - Home Soon",
  "Floatinurboat, ELLIØT - Limbo (feat. ELLIØT)",
  "DM Galaxy, Tyler Fiore, Disfigure - Paralyzed (Disfigure Remix)",
  "Elektronomia - Heaven",
  "Vanze, Reunify, Parker Polhill, Bibiane Z. - Angel (feat. Parker Polhill & Bibiane Z)",
  "Max Brhon - Pain",
  "Mekanism - Green Lights",
  "Fytch, Kosta, Theo Hoarau - Blinded (feat. Kosta & Theo Hoarau)",
  "Arcana, Zack Merci - Into The Wild",
  "Dread Pitt - Pyro",
  "High Maintenance, Charlotte Haining - Change Your Ways (feat Charlotte Haining)",
  "Heleen, BEAUZ - Alone",
  "James Burki, NCT - Hold On",
  "Papa Khan - I GOT YOU",
  "Cartoon, Koit Toome - Your Stories (feat. Koit Toome)",
  "Nito-Onna, BAUWZ, Poylow - Hate You",
  "Phantom Sage, Whales - One Day",
  "Cytrax, Émilie Rachel - Feelings",
  "Mandrazo, Julius Dreisig - Swalla",
  "Arcando, T-Rice - When I'm With You (T-Rice Remix)",
  "HYLO, Mikey Ceaser, AKACIA - Headstrong (feat. Mikey Ceaser & Akacia)",
  "SirensCeol - Stay",
  "CØDE - Don't Left Me",
  "iFeature - Party",
  "Isolated - Circus",
  "Max Landry, Zeus X Crona - Lights Turn Out",
  "NIVIRO - Demons",
  "BEAUZ, JVNA - Crazy",
  "THYKIER - INTENSIFY",
  "Castion, Uplink - Euphoria",
  "Unknown Brain, NotEvenTanner - Let You Go",
  "Laszlo - One Step Away",
  "Raptures., Sam Ourt - Taking Control ft. Halvorsen (berx Remix)",
  "Raptures. - Spark",
  "Kasger - Cover It Up",
  "Diviners, Rossy - Escape (feat. Rossy)",
  "Diamond Eyes - Flutter",
  "Micah Martin, CADMIUM, Rival - In Your Head (feat. Micah Martin)",
  "Whats Gud, Magnus - Sanity",
  "Waysons - Running",
  "ARZĘ, XØ SELF - dR3ÄMS",
  "Kyle Reynolds, Unknown Brain - I'm Sorry Mom",
  "PLEEG - Spirit",
  "OBLVYN, Riell - With You",
  "Mathew V, Arcando, Egzod - Runaway (feat. Mathew V)",
  "Facading - Freefalling",
  "Cesar Santolo, MANIA - Pick Up The Pieces (ft. Cesar Santolo)",
  "Axollo - Burn It",
  "Toxic Joy - Temptation",
  "Time To Talk, Cartoon - On & On (Time To Talk Remix)",
  "Holly, DRIVVIN - Til The End",
  "Acejax, INX, Danilyon - By My Side (feat. Danilyon)",
  "Vosai - Young & Wild & Free",
  "RIVERO, Anna Yvette - Heaven",
  "Desmeon - Hellcat",
  "TULE, Chris Linton - Fearless pt. II (feat. Chris Linton)",
  "T &amp; Sugah, NCT, Cammie Robinson - Find A Way (feat. Cammie Robinson)",
  "The Lifted, Man 3 Faces - Crash N Burn (feat. Man 3 Faces)",
  "CADMIUM, Chris Linton - Slow Down",
  "Charlotte Haining, Halcyon - Escape With Me (feat. Charlotte Haining)",
  "Cartoon, Kristel Aaslaid - Immortality (feat. Kristel Aaslaid)",
  "Brook Xiao, Rachel Horter - Fire",
  "1$K1 - GODSLAYER",
  "Endpoint, MIHXI, Carpö - Grey (ft. Endpoint)",
  "The Brig, MIDNIGHT CVLT - Can't Escape",
  "Too Martian, Shiah Maisel, NCT - News To Me",
  "Jim Yosef - Lights",
  "joegarratt - aya",
  "Dread Pitt, C - Reckless (ft. C.)",
  "intouch - Fighting Inside",
  "Halvorsen, Netrum - Circle",
  "VinDon, More Plastic - Patience",
  "RudeLies, Clarx - Erase",
  "Sam Ourt, Raptures. - Taking Control",
  "Daniel Levi - River",
  "Harley Bird, CHENDA, 32Stitches - Freedom",
  "Mike Vallas - Left My Heart In Pain",
  "Culture Code, Harley Bird - Feel Again (feat. Harley Bird)",
  "Vexento - Masked Raver",
  "Halcyon, Valentina Franco, Heuse - Runaway (Heuse Remix)",
  "Unknown Brain, Marvin Divine - MATAFAKA (feat. Marvin Divine)",
  "ROY KNOX - Shining",
  "Floatinurboat - Spirit Of Things",
  "Perk Pietrek, Abstrakt, Shiah Maisel - Running Away",
  "Lensko - Rebirth",
  "More Plastic - Take Me Back",
  "BRIGHTDVWN, VOLT VISION - Hide Your Heart",
  "Wubbaduck - Rush",
  "VENEMY, Danica - Need You Now (feat. Danica)",
  "Mykyl, Riggs, Elliot Kings - Paper Walls (with Mykyl)",
  "Robbie Rosen, jeonghyeon, Deerock, Vaance - Electric (feat. Robbie Rosen) (jeonghyeon Remix)",
  "Wiguez, P-One, borne - Pray Tonight (borne Remix)",
  "Electro-Light, Nathan Brumley - Night Shines (feat. Nathan Brumley)",
  "Coopex - I Miss You",
  "Fayzone, Valax, D'Amico - Mirage Of My Heart (ft. Fayzone)",
  "Disfigure - Hollah!",
  "Arcando, NCKD - When I'm With You (NCKD Remix)",
  "Maze, Trinist - Everything Will Be Okay.",
  "WATEVA, m els - Madness (feat. m els)",
  "Emdi, Veronica Bravo - Hurts Like This (feat. Veronica Bravo)",
  "Micah Martin, Doctor Neiman - Wait For Me",
  "Anna Yvette, AFK - Clouds",
  "LFZ, Meikal - Echoes (Meikal Remix)",
  "Culture Code, KARRA, Tobu - Make Me Move (feat. Karra) (Tobu Remix)",
  "Cartoon, Kristel Aaslaid - Immortality (feat. Kristel Aaslaid) (Remix)",
  "Raven &amp; Kreyn - In The Air ",
  "Rex Hooligan, Anna Simone - No More Levitation",
  "32Stitches - Uncharted",
  "Warptech, Cory Friesenhan - Resolution",
  "Neoni - LEVITATE",
  "Magnus, Alessia Labate, Unread - Cool",
  "Wiguez, Vizzen, Maestro Chives - Running Wild",
  "Ascence - Without You",
  "Everen Maxwell - Bot Fight",
  "Shiah Maisel, Arlow - 21",
  "Bri Tolani, Marvin Divine, Unknown Brain - Faceless",
  "Weero - Mates",
  "Abandoned, Mendum - Voyage",
  "Coral Oulu - Sympathy (feat. Coral Oulu)",
  "Dryskill, Max Brhon - War Machine",
  "Rameses B, SOUNDR - Good With It",
  "Raptures., MAZAN - Sweet",
  "Killa - Retro Love",
  "Tollef - Capsized",
  "Vizzen, Protolizard - Heaven Knows",
  "Wiguez, P-One - VBM (Ft. P-One)",
  "Alexa Lusader, OLWIK - Taking Over (feat Alexa Lusader)",
  "Unknown Brain, Rival, Jex - Control (feat. Jex)",
  "Agassi, EH!DE, Wiguez - The Path (Ft. Agassi)",
  "Zack Merci, Nieko - Psycho (feat. Nieko)",
  "Ash O'Connor - You",
  "T &amp; Sugah, MVE - Sleepless (feat. MVE)",
  "Ellis, Anna Yvette - Migraine (feat. Anna Yvette)",
  "Kovan, Mark Borino - Thrill Is Gone (feat. Mark Borino)",
  "URBANO, More Plastic - One Taste",
  "Brig - Spoil",
  "Krys Talk, Cole Sipe - Way Back Home",
  "JPB - Levitate",
  "CADMIUM, Rival, Futuristik, Whogaux - Seasons [Futuristik & Whogaux Remix] [Instrumental]",
  "Au5, Danyka Nadeau - Closer [Intrumental]",
  "Rival, CADMIUM, Rosendale - Willow Tree (feat. Rosendale)",
  "More Plastic - Let Me Go",
  "Culture Code - Not Giving In",
  "Wontolla, Kasger, Limitless - Miles Away",
  "Mendum, Omri - Beyond (feat. Omri)",
  "Eli Raain, Veronica Bravo, CADMIUM - Click & Scroll (feat. Eli Raain & Veronica Bravo)",
  "Robin Hustin, Tobimorrow - Light It Up",
  "Maze, Trinist - Would You Ever",
  "Krale, Jasmina Lin, Jay Christopher - Frontier (ft. Jasmina Lin & Jay Christopher)",
  "Near x Far - Not Enough",
  "Debris, Jonth - Game Time",
  "Tom Wilson - Be Myself",
  "Matthew Blake - Saved Me Now",
  "Mendum - One Third",
  "RedMoon, Meron Ryan - Heavyweight",
  "GALLIUM - All I Wanna",
  "BENIX, Dirty Palm - Legacy",
  "Mendum, Krys Talk - Stay With Me (Krys Talk Remix)",
  "Jim Yosef - Link",
  "Custody, Just Isac, MADZI, SFRNG - No Way Back",
  "Simon Says! - one more time (feat. Devonte)",
  "Polygon - Bring It Back",
  "Rob Roth, Lost Identities - For Me",
  "Netrum - Any Closer",
  "Siimi - Set You Free",
  "Arlow - Feel So Lucky",
  "K.Safo, Alex Skrindo, Stewart Wallace - Future Vibes (feat. Stewart Wallace)",
  "AXEN, HYLO - Habits (feat. AKACIA)",
  "ElementD, Chris Linton - Ascend",
  "3rd Prototype - Get In",
  "Syn Cole - Melodia",
  "Syntact - Ego",
  "Tobu - Memory Lane",
  "Last Heroes - Dimensions",
  "Mendum, xo sad - Save Myself (feat. xo sad)",
  "Tatsunoshin, Giin - Light Me Up (feat. Giin)",
  "Johnning - WHAT THE HELL",
  "Birch - Pray For You",
  "Itro - All For You (ft. SILIAS)",
  "CITYWLKR, Josh Rubin - Immortal (feat. Josh Rubin)",
  "JB Hain - feel",
  "Svniivan, WTCHOUT, ROY KNOX - Shadows (Feat. Svniivan)",
  "Stereotype - TOKYO 2099",
  "Tom Wilson, Jagsy, braev - All My Love",
  "Chime - Lifelong",
  "JOXION, EXYT - Testify",
  "Dave Marriner, Time To Talk - Say The Words",
  "Hayve, More Plastic - Feel Alive",
  "iFeature - Dreamatic",
  "Linn Sandin, Facading, Vosai - Crossed The Line",
  "JPB - High",
  "Diamond Eyes - Everything",
  "Nat James, Dirty Palm - King Of The Hill",
  "Godmode, LBLVNC - Power !",
  "JOXION - LA VIBE",
  "Barmuda, Andrew A - Fall Too Deep",
  "Nieko, Zack Merci - BOUNCE! (feat. Nieko)",
  "Le Malls - Come Through (feat. Ari G)",
  "Charlotte Sands, Unknown Brain - Last Thing ",
  "TULE - Lost",
  "Alaina Cross, Maestro Chives, Egzod - No Rival",
  "JOXION - Next Level",
  "Shiah Maisel, Electro-Light - Letter",
  "Jack Shore, Tollef - Dreaming Of Me",
  "Light Years Away - Melrose At Midnight",
  "Alex Skrindo - Falling Down",
  "Disco's Over - TSU",
  "Weero - Our Dive",
  "God's Warrior - By Your Side",
  "Zeus X Crona - Lose Me Too",
  "Fareoh - Under Water",
  "RMCM, James Roche, Micah Martin - Diamonds (feat. Micah Martin)",
  "Glude - Dreamers",
  "Zoe Moon, STAR SEED - Cayenne",
  "Koven - Looking For More",
  "ANGELPLAYA - DANGEROUS",
  "Aeden, Harley Bird - Find A Way Out",
  "Kontinuum, Savoi - Lost (feat. Savoi)",
  "Lensko - Sarvagon 2015",
  "Halvorsen - CTRL Z",
  "Lox Chatterbox, Unknown Brain, Salvo, BLVKSTN - Waiting (feat. Lox Chatterbox, BLVKSTN & Salvo)",
  "SirensCeol, Reaktion, The Eden Project - Let You Know",
  "VENEMY, Aznar, Doubletake - Reign",
  "Cole Phillips, Affe, Cartoon - On & On (Affe & Cole Phillips Remix)",
  "Fiveight, WATEVA - Get $",
  "Electronic Vibes, M.I.M.E - Don't Leave Me",
  "Abstrakt - U",
  "Trinist, Maze - Erase You",
  "nøll, Highlnd, Josh Rubin - Don't Want To Feel",
  "Sekai - Running",
  "Arcien - Elevate",
  "Kovan, Electro-Light - Skyline",
  "EBEN - Promise",
  "Futuristik - Like U Say",
  "Vaskan - Your Love",
  "Tollef - Take Our Time",
  "3rd Prototype - Shadows",
  "Janji, Johnning - Heroes Tonight (feat. Johnning)",
  "Daniel Levi - That's What Makes It Right",
  "Phantom Sage - Pendulum",
  "Juan Dileju, Sam Ourt, AKIAL - Escape (Juan Dileju & Sam Ourt VIP Mix)",
  "Josh Rubin - Surrender",
  "Waysons - Eternal Minds",
  "ElementD, Chordinatez, Mees van den Berg - Radiate (feat. Mees Van Den Berg)",
  "Neoni, Arcando, Besomorph - Army",
  "David Bulla - Unexpected",
  "Main Reaktor - Alone",
  "Rameses B - There For You",
  "Matthew Blake, Tyler Fiore - Upside Down",
  "Arcando, ThatBehavior - Ghost Town (feat. Vanessa Campagna)",
  "AX.EL - In Love With A Ghost",
  "Lynzz, Arya, borne - Need U",
  "imallryt, ROY KNOX, Hayve - Give Up On You",
  "ETikka, MADZI - Blind Heart",
  "Snowfyre - Primitive",
  "NIVIRO - Dancin'",
  "Ellis - Clear My Head",
  "Syn Cole - Feel Good",
  "Unknown Brain, Chris Linton - Saviour (feat. Chris Linton)",
  "Slashtaq, KALU - Neverland (feat. Kalu)",
  "ROY KNOX - I Wish",
  "Arlow - How Do You Know",
  "Konac - Home",
  "Tom Wilson, joegarratt - Until I Die ",
  "Guy Arthur - Runaway",
  "Vidya Vidya - Safari Fruits",
  "JJD, Azertion, Time To Talk - Street Lights",
  "Different Heaven - Safe & Sound",
  "Electro-Light, Nathan Brumley - Fall For Gravity Feat. Nathan Brumley",
  "Jonas Wang - Shining",
  "Dark Point, Alex Holmes - You Are",
  "Electro-Light, Jordan Kelvin James, Anna Yvette - Wait For You (feat. Anna Yvette)",
  "Deflo, AWA - Spotlight (feat. AWA)",
  "Different Heaven, EH!DE - My Heart",
  "Unknown Brain, Attxla - Roots (feat. Attxla)",
  "it's different, Miss Mary - Shadows (ft. Miss Mary)",
];
